mqtt:
  broker: 127.0.0.1:1883
  user: root
  pass: root
  topicToSubscribe: device/attributes
  topicToPublish: device/attributes
  topicToStatus: device/status
  topicToProgress: ota/device/progress
  topicToCommand: device/command
  topicToEvent: device/event
  topicToInform: ota/device/inform
  gateway_topic: gateway/attributes
  #消息服务质量 0：消息最多传递一次，如果当时客户端不可用，则会丢失该消息。1：消息传递至少 1 次。2：消息仅传送一次。
  qos: 0

mqtts:
  broker: 127.0.0.1:8883
  user: root
  pass: root
  caPath : ./conf/certificate/ca.crt
  crtPath: ./conf/certificate/client.crt
  keyPath : ./conf/certificate/client.key

api:
  http_host: 127.0.0.1:8083
